### ISSUE TITLE
cuda initialization failed

### ISSUE THREAD

**Issue by TITAINc** [antabangun/coex#3] opened 2021-09-07 15:36 UTC
Hello, there is a problem when I run demo.py

  File "demo.py", line 45, in <module>
    cfg=cfg).cuda()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.

Is there any solution?

**Comment by antabangun** [comment] 2021-09-09 13:09
Hi, the error indicates that your computer might not have a CUDA GPU. if you do not have a CUDA GPU, you can remove the parts in the demo code that requires CUDA so that the code would run on the CPU. You can try replacing demo.py with the following code:
```python
import cv2
import numpy as np
import time

import torch
from torch.utils.data import DataLoader

from ruamel.yaml import YAML

from dataloaders import KITTIRawLoader as KRL

from stereo import Stereo

torch.backends.cudnn.benchmark = True


torch.set_grad_enabled(False)

config = 'cfg_coex.yaml'
version = 0  # CoEx

vid_date = "2011_09_26"
vid_num = '0093'
half_precision = True

def load_configs(path):
    cfg = YAML().load(open(path, 'r'))
    backbone_cfg = YAML().load(
        open(cfg['model']['stereo']['backbone']['cfg_path'], 'r'))
    cfg['model']['stereo']['backbone'].update(backbone_cfg)
    return cfg

if __name__ == '__main__':
    cfg = load_configs(
        './configs/stereo/{}'.format(config))

    ckpt = '{}/{}/version_{}/checkpoints/last.ckpt'.format(
        'logs/stereo', cfg['model']['name'], version)
    cfg['stereo_ckpt'] = ckpt
    pose_ssstereo = Stereo.load_from_checkpoint(cfg['stereo_ckpt'],
                                                strict=False,
                                                cfg=cfg)

    left_cam, right_cam = KRL.listfiles(
        cfg,
        vid_date,
        vid_num,
        True)
    cfg['training']['th'] = 0
    cfg['training']['tw'] = 0
    kitti_train = KRL.ImageLoader(
        left_cam, right_cam, cfg, training=True, demo=True)
    kitti_train = DataLoader(
        kitti_train, batch_size=1,
        num_workers=4, shuffle=False, drop_last=False)
    
    fps_list = np.array([])

    pose_ssstereo.eval()
    for i, batch in enumerate(kitti_train):
        start = time.time()

        imgL, imgR = batch['imgL'], batch['imgR']
        imgLRaw = batch['imgLRaw']
        imgLRaw = imgLRaw

        runtime = time.time() - start
        print('Data Preparation: {:.3f}'.format(runtime))

        start = time.time()

        disp = pose_ssstereo(imgL, imgR, False)

        runtime = time.time() - start
        print('Stereo runtime: {:.3f}'.format(runtime))

        fps = 1/runtime
        fps_list = np.append(fps_list, fps)
        if len(fps_list) > 5:
            fps_list = fps_list[-5:]
        avg_fps = np.mean(fps_list)
        print('Stereo runtime: {:.3f}'.format(1/avg_fps))

        disp_np = (2*disp[0]).data.cpu().numpy().astype(np.uint8)
        disp_np = cv2.applyColorMap(disp_np, cv2.COLORMAP_PLASMA)

        image_np = (imgLRaw[0].permute(1, 2, 0).data.cpu().numpy()).astype(np.uint8)
        
        out_img = np.concatenate((image_np, disp_np), 0)
        cv2.putText(
            out_img,
            "%.1f fps" % (avg_fps),
            (10, image_np.shape[0]+30),
            cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        cv2.imshow('img', out_img)
        cv2.waitKey(1)
```
But I do not recommend running the code in CPU, as it is very slow :(( (About 0.8 fps on mine).

**Comment by antabangun** [comment] 2021-09-12 07:06
Hi, I assume the issue is solved and will be closing this issue now.

**Closed by antabangun** 2021-09-12 07:06 UTC

**Comment by TITAINc** [comment] 2021-09-12 07:15
I'm sorry to reply to you now, thank you for answering my question seriously, I tried the method you proposed, and finally reduced the pytorch and other related configuration versions to solve the problem.

**Comment by antabangun** [comment] 2021-09-12 07:37
That's great to hear!
